DGM_Checkout_Dev/DGM_Checkout_Dev/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DGM_Checkout_dev.Data;
using DGM_Checkout_dev.Models;
using Microsoft.AspNetCore.Authorization;

namespace DGM_Checkout_dev.Controllers
{
    [Authorize]
    public class InventoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InventoriesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Inventories
        /// <summary>
        /// Added search functions to Index method
        /// Search can be moved to it's own Search method or partial view to eliminate clutter from Index
        /// </summary>
        /// <param name="serialNumberSearch"></param>
        /// <param name="nameSearch"></param>
        /// <param name="makeSearch"></param>
        /// <param name="modelSearch"></param>
        /// <param name="costSearch"></param>
        /// <param name="locationSearch"></param>
        /// <param name="rentalSearch"></param>
        /// <param name="statusSearch"></param>
        /// <param name="typeSearch"></param>
        /// <param name="costRadio"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string serialNumberSearch, string nameSearch, string makeSearch, string modelSearch, int costSearch, string locationSearch, string rentalSearch, string statusSearch, string typeSearch, string costRadio)
        {
            ViewData["serialNumberSearch"] = serialNumberSearch;
            ViewData["nameSearch"] = nameSearch;
            ViewData["makeSearch"] = makeSearch;
            ViewData["modelSearch"] = modelSearch;
            ViewData["costSearch"] = costSearch;
            ViewData["locationSearch"] = locationSearch;
            ViewData["rentalSearch"] = rentalSearch;
            ViewData["statusSearch"] = statusSearch;
            ViewData["typeSearch"] = typeSearch;

            var inventory = from i in _context.Inventory
                            .Include(i => i.Location)
                            .Include(i => i.Rental)
                            .Include(i => i.Status)
                            .Include(i => i.Type)
                            select i;

            if(!String.IsNullOrEmpty(serialNumberSearch))
            {
                inventory = inventory.Where(i => i.InventorySerialNumber.Contains(serialNumberSearch));
            }
            if (!String.IsNullOrEmpty(nameSearch))
            {
                inventory = inventory.Where(i => i.InventoryName.Contains(nameSearch));
            }
            if (!String.IsNullOrEmpty(makeSearch))
            {
                inventory = inventory.Where(i => i.InventoryMake.Contains(makeSearch));
            }
            if (!String.IsNullOrEmpty(modelSearch))
            {
                inventory = inventory.Where(i => i.InventoryModel.Contains(modelSearch));
            }
            if (!String.IsNullOrEmpty(locationSearch))
            {
                inventory = inventory.Where(i => i.Location.LocationEntry.Contains(locationSearch));
            }
            if (!String.IsNullOrEmpty(rentalSearch))
            {
                inventory = inventory.Where(i => i.Rental.RentalName.Contains(rentalSearch));
            }
            if (!String.IsNullOrEmpty(typeSearch))
            {
                inventory = inventory.Where(i => i.Type.TypeEntry.Contains(typeSearch));
            }
            if(costRadio is "greater")
            {
                inventory = inventory.Where(i => i.InventoryCost > costSearch);
            }
            if(costRadio is "less")
            {
                inventory = inventory.Where(i => i.InventoryCost < costSearch);
            }
            if(costRadio is "equal")
            {
                inventory = inventory.Where(i => i.InventoryCost.Equals(costSearch));
            }     
            return View(await inventory.AsNoTracking().ToListAsync());
        }

        // GET: Inventories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .Include(i => i.Location)
                .Include(i => i.Rental)
                .Include(i => i.Status)
                .Include(i => i.Type)
                .SingleOrDefaultAsync(m => m.InventoryID == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Inventories/Create
        public IActionResult Create()
        {
            ViewData["LocationID"] = new SelectList(_context.Location, "LocationID", "LocationEntry");
            ViewData["RentalID"] = new SelectList(_context.Rental, "RentalID", "RentalName");
            ViewData["StatusID"] = new SelectList(_context.Status, "StatusID", "StatusEntry");
            ViewData["TypeID"] = new SelectList(_context.Type, "TypeID", "TypeEntry");
            return View();
        }

        // POST: Inventories/Create
        /// <summary>
        /// Edited the Create method to prevent overposting to InventoryID
        /// </summary>
        /// <param name="inventory"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InventorySerialNumber,InventoryName,InventoryMake,InventoryModel,InventoryNotes,InventoryCost,TypeID,LocationID,StatusID")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inventory);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["LocationID"] = new SelectList(_context.Location, "LocationID", "LocationEntry", inventory.LocationID);
            //ViewData["RentalID"] = new SelectList(_context.Rental, "RentalID", "RentalName", inventory.RentalID);
            ViewData["StatusID"] = new SelectList(_context.Status, "StatusID", "StatusEntry", inventory.StatusID);
            ViewData["TypeID"] = new SelectList(_context.Type, "TypeID", "TypeEntry", inventory.TypeID);
            return View(inventory);
        }

        // GET: Inventories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .Include(i => i.Location)
                .Include(i => i.Status)
                .Include(i => i.Rental)
                .Include(i => i.Type)
                .SingleOrDefaultAsync(m => m.InventoryID == id);
            if (inventory == null)
            {
                return NotFound();
            }
            ViewData["LocationID"] = new SelectList(_context.Location, "LocationID", "LocationEntry", inventory.LocationID);
            ViewData["RentalID"] = new SelectList(_context.Rental, "RentalID", "RentalName", inventory.RentalID);
            ViewData["StatusID"] = new SelectList(_context.Status, "StatusID", "StatusEntry", inventory.StatusID);
            ViewData["TypeID"] = new SelectList(_context.Type, "TypeID", "TypeEntry", inventory.TypeID);
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        /// <summary>
        /// EditPost now only updates the fields listed in the TryUpdateModelAsync statement
        /// Prevents overposting and changing values of any attribute not listed in the rentalUpdate list
        /// see https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud for details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }
            var inventoryUpdate = await _context.Inventory.SingleOrDefaultAsync( i => i.InventoryID == id);

            if(await TryUpdateModelAsync<Inventory>( inventoryUpdate, "", i => i.InventoryNotes, i => i.LocationID, i => i.StatusID, i => i.RentalID))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again and if problems continue contact IT support.");
                }
            }
            
            ViewData["LocationID"] = new SelectList(_context.Location, "LocationID", "LocationEntry", inventoryUpdate.LocationID);
            ViewData["RentalID"] = new SelectList(_context.Rental, "RentalID", "RentalName", inventoryUpdate.RentalID);
            ViewData["StatusID"] = new SelectList(_context.Status, "StatusID", "StatusEntry", inventoryUpdate.StatusID);
            ViewData["TypeID"] = new SelectList(_context.Type, "TypeID", "TypeEntry", inventoryUpdate.TypeID);
            return View(inventoryUpdate);
        }

        // GET: Inventories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .Include(i => i.Location)
                .Include(i => i.Rental)
                .Include(i => i.Status)
                .Include(i => i.Type)
                .SingleOrDefaultAsync(m => m.InventoryID == id);
            if (inventory == null)
            {
                return NotFound();

DGM_Checkout_Dev/DGM_Checkout_Dev/Views/Shared/_InventoryPartial.cshtml
@using DGM_Checkout_dev.Models
@model IEnumerable<DGM_Checkout_dev.Models.Inventory>


@{
@foreach (var item in Model)
{        if(item.RentalID == null)
    {
        @Html.DisplayFor(modelItem => item.InventoryName)

    }
        <td>
            @Html.DisplayFor(modelItem => item.InventorySerialNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InventoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InventoryMake)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InventoryModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InventoryCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location.LocationEntry)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rental.RentalName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.StatusEntry)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type.TypeEntry)
        </td>
    <tr>
        <td>
            <a asp-action="Edit" asp-route-id="@item.InventoryID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.InventoryID">Details</a>
        </td>
    </tr>
}
}

DGM_Checkout_Dev/DGM_Checkout_Dev/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DGM Checkout (dev)</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DGM Checkout (dev)</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Students</a></li>

                    <li class="dropdown">
                        <a asp-controller="Rentals" asp-action="Index" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rentals<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Rentals" asp-action="Index">View All</a></li>
                            <li><a asp-controller="Rentals" asp-action="Create">Create</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="Search">Search</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="Returns">Return</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Inventories" asp-action="Index">Inventory</a></li>

                    @* Reports *@
                    <li class="dropdown">
                        <a asp-controller="Reports" asp-action="Index" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Rentals" asp-action="Index">All Reports</a></li>
                            <li><a asp-controller="Rentals" asp-action="RentalsOut">Rentals Out</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="LateFeeNotPaid">Late(Fee Not Paid)</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="RentalUser">Rentals by User Search</a></li>
                        </ul>
                    </li>

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>

            

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="full-width-bar">
            <div class="container">
                <p class="text-muted">&copy; 2017 - DGM Checkout (dev)</p>
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>